aws_dbt_snowflake_project:
  outputs:
    dev:
      account: " "
      database: " "
      password: " "
      role: ACCOUNTADMIN
      schema: " "
      threads: 1
      type: snowflake
      user: " "
      warehouse: " "
  target: dev
