aws_dbt_snowflake_project:
  outputs:
    dev:
      account: UEXZHTT-MT62552
      database: AIRBNB
      password: Maheshwari@1616
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: MAHIYERGUDE
      warehouse: COMPUTE_WH
  target: dev
